# Generated by Django 5.1.5 on 2025-03-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='type',
            field=models.CharField(choices=[('MULTI', 'mulitple ads'), ('SINGLE', 'Full lenthg ad'), ('PRODUCT', 'PRO page ad')], default='MULTI', max_length=7),
        ),
    ]
